### ISSUE TITLE
Content is not always shown

### ISSUE THREAD

**Issue by Atrejoe** [Atrejoe/MarkdownPreview#1]
Content is not always displayed in the preview pane. This seems to be related to an issue where a `webbrowser` control does not always update.

The strange thing is that the source can be viewed and contains the proper content.

The following suggestions have been tried:
1. http://weblogs.asp.net/http://weblogs.asp.net/gunnarpeipman/displaying-custom-html-in-webbrowser-controlgunnarpeipman/displaying-custom-html-in-webbrowser-control
2. http://stackoverflow.com/questions/5362591/how-to-display-the-string-html-contents-into-webbrowser-control

The SharpShell Server Manager Test Shell _does_ always work.

**Comment by Atrejoe** [comment]
See [releases/tag/v0.3-alpha](https://github.com/Atrejoe/MarkdownPreview/releases):
- Display is fixed by not docking the canvas, but filling it up to 1px on all sides.
- Added embedded CSS from https://github.com/nicolashery/markdownpad-github

**Comment by Aaltuj** [comment]
come on man fix this already ;)

**Comment by Atrejoe** [comment]
This seems to have been fixed in 070e9945d39e4023d996784719285185de22edf5, I will release a new version shortly!

**Comment by Atrejoe** [comment]
Marked as fixed by release [0.6-alpha](../releases/tag/0.6-alpha)
