### ISSUE TITLE
Insallation easy way please )

### ISSUE THREAD

**Issue by sv-dev** [Atrejoe/MarkdownPreview#4]
Hello!

Thank you for very useful utility. But I am not a geek, help me please (
Can I use this for installation?
http://www.winhelponline.com/blog/previewconfig-tool-registers-file-types-for-the-preview-pane-in-windows-vista/

**Comment by Atrejoe** [comment]
Hi @sv-dev,

Unfortunately there is no simple yes-yes-yes type of installer, but with the Sharpshell Server Registration Manager, which you can download at: https://github.com/dwmkerr/sharpshell/releases/ (choose ServerManager.zip), it's pretty close: you open the registration manager, select the dll you have extracted (MarkdownPreview.dll), click `Install Server (x86)` and `Register Server (x86)`.

See: https://github.com/Atrejoe/MarkdownPreview/issues/2#issuecomment-249137122 for screenshots.

You might have to restart explorer.exe, either by killing it and starting it manually or rebooting :(

Good luck!

**Comment by Atrejoe** [comment]
You might have to restart explorer.exe, either by killingit and starting it manually or rebooting :(

**Comment by ewa** [comment]
This doesn't seem to recognize / correctly process the previewer.  I'm using your 0.3 package and  ServerManager version 2.2.0.0

![image](https://user-images.githubusercontent.com/288020/29847902-20acba18-8cdb-11e7-83b4-327708c93ca7.png)

**Comment by ewa** [comment]
Also, there's an unhandled exception when attempting to install from the command line:  

```
C:\Users\ewa\Downloads\MarkdownPreview.0.3>..\ServerManager\srm\srm.exe install
MarkdownPreview.dll

========================================
SharpShell - Server Registration Manager
========================================

An unhandled exception occured when loading the SharpShell
Server Types from the specified assembly. Is it a SharpShell
Server Assembly?

Unhandled Exception: System.NullReferenceException: Object reference not set to
an instance of an object.
   at ServerRegistrationManager.Application.InstallServer(String path, Registrat
ionType registrationType, Boolean codeBase)
   at ServerRegistrationManager.Application.Run(String[] args)
   at ServerRegistrationManager.Program.Main(String[] args)
```

![image](https://user-images.githubusercontent.com/288020/29848134-0f2f2996-8cdc-11e7-89af-b3b3dc9b588b.png)

**Comment by Atrejoe** [comment]
@ewa Are you on a x64 machine?
I have had the same issue using the command prompt on my x64 machine, but with the server manager I usually was successful. But now I use the packaged version downloaded from Github, I'm unsuccessful too.

I just compiled this in debug/any cpu mode and this seems to work fine, can you try if this works for you too? (see attachment)

[MarkdownPreview.zip](https://github.com/Atrejoe/MarkdownPreview/files/1266530/MarkdownPreview.zip)

**Comment by josineto** [comment]
@Atrejoe Perhaps [Sumatra PDF](https://github.com/sumatrapdfreader/sumatrapdf), which registers a very robust and lightweight `PreviewHandler` IMO, could bring an insight to the installation process.

**Comment by ewa** [comment]
@Atrejoe, sorry, I didn't see your comment at the time.  I am using an x64 machine.  Should I still try the version you attached or has progress marched on?

**Comment by Atrejoe** [comment]
@jzeneto Sumatra PDF uses C++, I'm mere standing on the shoulders of giants: SharpShell, which should take care of preview handler registration.

@ewa I'm using x64 too (both Win8 as Win10), and it 'works on my machine' (TM)
As I'm no expert on Windows development, and I'm not very much into SharpShell either, progress on the extension does not go fast.

(sorry about the late reply, somehow I'm missing these comments as well)
