### ISSUE TITLE
No instructions given for installation

### ISSUE THREAD

**Issue by kwbBaker** [Atrejoe/MarkdownPreview#6]
The installation section in the README just says to download it.  That's not installing it.  There isn't even an EXE to run.  How is someone expected to know how to install it?

**Comment by Atrejoe** [comment]
Hi @kwbskf,

That's why it also says:
>Until I've found a proper way for creating an installer for this extension, the best way to install the Markdown Shell Extension is by using Sharpshells' Server Manager Tool, which can be found at: SharpShell releases on GitHub. *The original text contains links*

Given that Sharpshell has released a new version, I may be able to use that to create a basic installation script.

I don't feel like documenting the usage of that tool here, but I think usage is somewhat straightforward (load dll, install, register, done).

**Comment by Atrejoe** [comment]
Marked as fixed by release [0.6-alpha](../releases/tag/0.6-alpha)

**Comment by kwbBaker** [comment]
Just by the way, I don't see any of that text you quoted in the README.md of the MarkdownPreview project.  Yes, there is a link to the SharpShells project, but no instructions saying to use it or how.  Now, of course, that has been changed to point to a new installers page, whose text in turn is struck-out because it isn't working (a work in progress, I'm sure).  Explicit text like what you quoted above (where was that supposed to be, anyway?) would still be useful, but even then, I have not been able to find any mention of "Sharpshells' Server Manager Tool" on the SharpShells README.md either.  I wonder if you are actually thinking of this:  https://github.com/dwmkerr/sharpshell/blob/master/docs/srm/srm.md ?
