### ISSUE TITLE
Local pictures cannot be displayed in the preview pane

### ISSUE THREAD

**Issue by laoqiuqiu** [Atrejoe/MarkdownPreview#9]

**Comment by laoqiuqiu** [comment]
inster to Engine.cs 26 line
`<base href="file:///{MD File Path}">`
The path ends with "\", `D:\.net\MarkdownPreview-master\`.

**Comment by Atrejoe** [comment]
I think the browser panel is not allowed to access local content.
See also the ReadMe.md file in this repo, on my machine the relative image is not shown.

![image](https://user-images.githubusercontent.com/585091/64129978-b758ab80-cdbf-11e9-8095-1d4d5861fb81.png)
